### PR TITLE
feat: Added support for RestIot plus

### PR DESCRIPTION
**Pull request by w1ll1am23**
This is hopefully all that is needed in order to get the 2nd gen plus to work. 

@trevorglaser can you test this by cloning this repo and running `python3 stub.py`?

It will prompt for your username and then password, and it will then loop over all of your stored favorites and play them each for 5 seconds.

### CODE REVIEW

**Comment by w1ll1am23** [comment]
@trevorglaser good deal, thanks for testing. The stub probably failed because the library would have needed to be installed to get all the dependencies installed first. That's no big deal. 

I'll have to do some testing around the light as well. There are some complications with allowing HA to turn the light on and off independently from the favorite selection. The biggest issue is that HA can send a command to turn on but that command has zero data around what to set on the light for brightness and color. Since the hatch API doesn't store that previous state, I had to cache it in the library. 

There is a pretty good chance that there is some bug in how I update the cached value resulting in the next on command to send a 0% brightness or something. 

Next time you see it, double check what the hatch app shows for the light state.

**Comment by w1ll1am23** [comment]
I discovered a flaw in my favorite selection plan. You aren't able to name favorites. They are named by the sound you are playing, meaning if you pick Ocean for more than one favorite they will both have the name ocean. My only thought, which isn't great, is to postfix the name with the favorite ID since that's really the only unique thing.

**Comment by w1ll1am23** [comment]
@trevorglaser okay, I believe I have everything working in this change + the custom component change. Found the issue with the light, and appended the favorite names with the IDs to fix favs that have the same name issue I mentioned above.

Can you test these changes again? Need this lib change and the updates over on the other repo

**Comment by trevorglaser** [comment]
I am just dropping the files directly into HA which is running python 3.9.

**Comment by w1ll1am23** [comment]
@dahlb thoughts here? Since Home Assistant supports 3.9? 

@trevorglaser what type of install are you running? Any chance you can upgrade to 3.10? I'm assuming hassos installs are running 3.10

**Comment by w1ll1am23** [comment]
I managed to create a new 3.10 virtual env and this is working for me now.

**Comment by trevorglaser** [comment]
I will work on upgrading to 3.10 this afternoon. I don't run hassio, I just run my HA on Debian.  And yes I can send debug logs for the battery.

**Comment by trevorglaser** [comment]
@w1ll1am23 I am still working on the Python 3.9 to 3.10 upgrade. I have tried many times and am having weird errors pop up every time. I'll let you know when I get it figured out.

**Comment by w1ll1am23** [comment]
@trevorglaser won't be able to support 3.9 once this merges without a bunch of changes, but pushed up a branch that has support for only gen 2 devices and should work with 3.9. If you want to just test out these library changes/get those logs.

https://github.com/w1ll1am23/ha_hatch/tree/gen_2_python3.9

**Comment by trevorglaser** [comment]
Here is the error that I got:
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/loader.py", line 722, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/loader.py", line 739, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/ha_hatch/media_player.py", line 14, in <module>
    from .rest_media_entity import RestMediaEntity
  File "/home/homeassistant/.homeassistant/custom_components/ha_hatch/rest_media_entity.py", line 24, in <module>
    from .rest_entity import RestEntity
  File "/home/homeassistant/.homeassistant/custom_components/ha_hatch/rest_entity.py", line 8, in <module>
    class RestEntity(ABC):
  File "/home/homeassistant/.homeassistant/custom_components/ha_hatch/rest_entity.py", line 9, in RestEntity
    def __init__(self, rest_device: RestMini | RestPlus, entity_type: str):
TypeError: unsupported operand type(s) for |: 'type' and 'type'

**Comment by trevorglaser** [comment]
Here is the error that I got.
```
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/loader.py", line 722, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/loader.py", line 739, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/ha_hatch/media_player.py", line 14, in <module>
    from .rest_media_entity import RestMediaEntity
  File "/home/homeassistant/.homeassistant/custom_components/ha_hatch/rest_media_entity.py", line 24, in <module>
    from .rest_entity import RestEntity
  File "/home/homeassistant/.homeassistant/custom_components/ha_hatch/rest_entity.py", line 8, in <module>
    class RestEntity(ABC):
  File "/home/homeassistant/.homeassistant/custom_components/ha_hatch/rest_entity.py", line 9, in RestEntity
    def __init__(self, rest_device: RestMini | RestPlus, entity_type: str):
TypeError: unsupported operand type(s) for |: 'type' and 'type'
```

**Comment by w1ll1am23** [comment]
I missed a file, swap out that rest_entity.py with the one from the latest push and try again.

**Comment by dahlb** [comment]
Might be able to support union in 3.9 with 'from __future__ import
annotations'. https://peps.python.org/pep-0604/ I keep my project in line
with python 3.10 because the docker/haos use that version and I've had
error in aiohttp when I wasn't in step with the official version

**Comment by w1ll1am23** [comment]
@dahlb Nice! that seems to work for me in my venv running 3.9. Looks like that was already in place on all of the files but the rest_entity.py

@trevorglaser feel free to switch back over to the branch in this PR https://github.com/dahlb/ha_hatch/pull/25 and just test that out directly.

**Comment by w1ll1am23** [comment]
@dahlb @trevorglaser has tested these changes and everything is working. This is ready for your review

**Pull request merged**
